//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaProject_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Skills
    {
        public int SkilssID { get; set; }
        public string SkillName { get; set; }
        public Nullable<byte> Percentage { get; set; }
        public string Description { get; set; }
    }
}
